const GET_PART = 'GET_PART';
const SUCCESS_GET_PART = 'SUCCESS_GET_PART';
const FAIL_GET_PART = 'FAIL_GET_PART';

const GET_ALL_PART = 'GET_ALL_PART';
const SUCCESS_GET_ALL_PART = 'SUCCESS_GET_ALL_PART';
const FAIL_GET_ALL_PART = 'FAIL_GET_ALL_PART';

const ADD_PART = 'ADD_PART';
const SUCCESS_ADD_PART = 'SUCCESS_ADD_PART';
const FAIL_ADD_PART = 'FAIL_ADD_PART';

const DEL_PART = 'DEL_PART';
const SUCCESS_DEL_PART = 'SUCCESS_DEL_PART';
const FAIL_DEL_PART = 'FAIL_DEL_PART';

const GET_CONTRACT = 'GET_CONTRACT';
const SUCCESS_GET_CONTRACT = 'SUCCESS_GET_CONTRACT';
const FAIL_GET_CONTRACT = 'FAIL_GET_CONTRACT';

const GET_ALL_CONTRACT = 'GET_ALL_CONTRACT';
const SUCCESS_GET_ALL_CONTRACT = 'SUCCESS_GET_ALL_CONTRACT';
const FAIL_GET_ALL_CONTRACT = 'FAIL_GET_ALL_CONTRACT';

const ADD_CONTRACT = 'ADD_CONTRACT';
const SUCCESS_ADD_CONTRACT = 'SUCCESS_ADD_CONTRACT';
const FAIL_ADD_CONTRACT = 'FAIL_ADD_CONTRACT';

const DEL_CONTRACT = 'DEL_CONTRACT';
const SUCCESS_DEL_CONTRACT = 'SUCCESS_DEL_CONTRACT';
const FAIL_DEL_CONTRACT = 'FAIL_DEL_CONTRACT';



